on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write
  actions: read

jobs:
  test-python:
    uses: NERC-CEH/dri-cicd/.github/workflows/test-python.yml@main
    with:
      use_uv: true
      coverage_threshold: 90
      use_pyright: true
      localstack_profile_name: localstack

  build-test-deploy-docker:
    needs: [test-python]
    uses: NERC-CEH/dri-cicd/.github/workflows/build-test-deploy-docker.yml@main
    with:
      use_uv: true
      package_name: geospatial_api
    secrets:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
